### ISSUE TITLE
Google Calendar Integration 

### ISSUE THREAD

**Issue by tarekait1996** [Concordia-Campus-Guide/Concordia-Campus-Guide#10]
As a student, I would like to be able to link my google calendar to the app so that I can get directions for my upcoming class.

Acceptance Criteria
~- The system should let the user choose between multiple calendars if he has more than one.~
~- The user should get notified prior to his class starting, and have the option to get directions~
Given that I am a student,
and then I click on the Google Calendar Icon.
then I should be able to:

- Choose to give access or not to my Google Calendar.

Tech tasks:
- Define the contract int he google event that is required to be understood by the add and the other methods

**Comment by imabhijit** [comment]
PR: https://github.com/Concordia-Campus-Guide/Concordia-Campus-Guide/pull/92
