### ISSUE TITLE
Display a better name for rooms in the list view of the Search Activity

### ISSUE THREAD

**Issue by ferdousara-parvin** [Concordia-Campus-Guide/Concordia-Campus-Guide#138]
**Description**
As shown in the screenshot below, there is a redundancy in the room name since we are taking the floor code AND the room code. 

**Goals**
Instead of how it is written in the screenshot below. It would be written "H819", "H821", etc for the rooms. In other words, the room name displayed should be the building code AND the room code.

**Reference to User stories**
#38 

**Difficulty (Scale 1-10)**
3

**Additional documentation (Optional)**
Currently, it looks like this: 
![image](https://user-images.githubusercontent.com/32084900/77178569-a04c8300-6a9d-11ea-8969-9dc376dfd9c5.png)

**Comment by viveanban** [comment]
This would only apply for rooms in the H and VL. Rooms in the MB building need their floor code to be identifiable.

**Comment by viveanban** [comment]
As this problem does not have a consistent solution for all buildings, we have decided to keep the displayed room names as it is (with both the floor code and room code).
