### ISSUE TITLE
Side Menu UI

### ISSUE THREAD

**Issue by thomasgauvin** [Concordia-Campus-Guide/Concordia-Campus-Guide#156]
As a user, I would like to be able to toggle my preferences from a side menu, so that I can customize the behavior of the application.

Description: This story involves creating a side menu that is accessible from the main page. It will open upon click of the hamburger menu as per our UI design. Coordination with other preferences stories is expected.

Acceptance criteria:
Given that I am on the main page,
and that I clicked on the hamburger icon
then I should see,
- A side menu popping up on the left side of the application as an overlay on top of the main page as designed in our Figma mockups

Story tasks:
1. Implement side menu
2. Testing

**Comment by tarekait1996** [comment]
<img width="178" alt="Screen Shot 2020-04-02 at 7 35 55 PM" src="https://user-images.githubusercontent.com/34817695/78309587-60fc4880-7519-11ea-99c6-f398be833a30.png">
