### ISSUE TITLE
Set mode of transportation dynamically in the code

### ISSUE THREAD

**Issue by ferdousara-parvin** [Concordia-Campus-Guide/Concordia-Campus-Guide#163]
**Description**
We have hardcoded the transport type to always be "TRANSIT" for now. Eventually, we would want the transport type to change dynamically based on the icon clicked on the Routes Activity page.

**Goals**
The goal is to allow the user to choose which mode of transportation they would like.

**Reference to User stories**
#94 

**Difficulty (Scale 1-10)**
4

**Additional documentation (Optional)**
Links to images, mockups, layouts

**Comment by thomasgauvin** [comment]
@ferdousara-parvin we should aim to get this done in this sprint

**Comment by ferdousara-parvin** [comment]
> 
> 
> @ferdousara-parvin we should aim to get this done in this sprint

Absolutely, I put it in Milestone 3! I just put this as a reminder because I forgot about it.

**Comment by Hambrsoom** [comment]
Who should be assigned to this ? @ferdousara-parvin  are you handling it ?
