### ISSUE TITLE
Google Calendar Next Class Directions

### ISSUE THREAD

**Issue by thomasgauvin** [Concordia-Campus-Guide/Concordia-Campus-Guide#17]
As a student, I would like to easily get directions to my next class as indicated in my Google Calendar, so that I can easily get to my next class.

Acceptance Criteria
Given that I gave access to my Google Calendar,
then, I should be able to:
- select the directions to my next class.
- get the locations and direction to my upcoming classes based on the next calendar event.

![image](https://user-images.githubusercontent.com/35609369/75820275-0d57dd00-5d6a-11ea-9871-36f4156a55bd.png)

**Comment by narrapangan** [comment]
### Calendar Event Format 
This is the format that the user must follow when entering their classes on their calendar in order for the parsing to work correctly.

- Calendar Event Title
User must specify if it is a "Lecture: ", a "Tutorial: " or a "Lab: "
User must enter class name 
Eg. "Lecture: SOEN 357"

- Calendar Event Location
User must specify floor code and room code with a ", " in between
Eg. "H-9, 963"
