### ISSUE TITLE
Write logic of onClickDisability() method

### ISSUE THREAD

**Issue by ferdousara-parvin** [Concordia-Campus-Guide/Concordia-Campus-Guide#180]
**Description**
onClickDisability() method in RoutesActivity.java is currently empty since we will only work on user stories related to catering to disabled people in Sprint 4

**Goals**
Write the logic of onClickDisability() during Sprint 4.

**Reference to User stories**
Epic 6: #159 and #160 I'm guessing

**Difficulty (Scale 1-10)**
5

**Additional documentation (Optional)**
Links to images, mockups, layouts

**Comment by viveanban** [comment]
What changes are expected when we click on the disability button?
