### ISSUE TITLE
CCG- #3 - As a user, I would like to see the maps of my surroundings, and easily see the Concordia Loyola Campus or the SGW Campus, so that I can visualize campus surroundings.

### ISSUE THREAD

**Issue by Hambrsoom** [Concordia-Campus-Guide/Concordia-Campus-Guide#188]
| **AT-1** | CCG- #3 - As a user, I would like to see the maps of my surroundings, and easily see the Concordia Loyola Campus or the SGW Campus, so that I can visualize campus surroundings. |
| --- | --- |
| **Acceptance Criteria** | <p> Given that I just open the application,<br> then I should see the map and switch between the campus. </p>|
| **Result** |  80% completed |
| **Comments** | The Campus switching buttons. Make Them darker  and put them in the middle  |

**Comment by viveanban** [comment]
![CCG3](https://user-images.githubusercontent.com/32105523/77878762-1338c500-7227-11ea-8493-821a794051e3.gif)

**Comment by viveanban** [comment]
![CCG3](https://user-images.githubusercontent.com/32105523/77880771-6ca2f300-722b-11ea-9866-7e0c71fdb618.gif)

**Comment by thomasgauvin** [comment]
In this acceptance test, we show that the campus switcher buttons were made darker and moved to the middle of the screen, as per the comments at our last meeting.

**Comment by mosaliza** [comment]
Put the zoom level so that all the buildings on the campuses can be seen as you switch between them.

**Comment by thomasgauvin** [comment]
fixed as part of https://github.com/Concordia-Campus-Guide/Concordia-Campus-Guide/pull/241

**Comment by mosaliza** [comment]
Passed.

**Comment by Hambrsoom** [comment]
![image](https://user-images.githubusercontent.com/32947679/79882794-202d7c00-83c1-11ea-88cd-b63539269bbb.png)
