### ISSUE TITLE
CCG-4 - As a user, I would like to visualize the building that I am currently in so that I can know my location.

### ISSUE THREAD

**Issue by Hambrsoom** [Concordia-Campus-Guide/Concordia-Campus-Guide#189]
| **AT-2** | CCG- #4 - As a user, I would like to visualize the building that I am currently in so that I can know my location. |
| --- | --- |
| **Acceptance Criteria** | <p>Given that I am using the map,<br>then, I should be able to:<br><ul><li>see my current location accurately on the map which is indicated by a pin.</li><li>see the location pin moving according to my movements if I am moving around, it should be constantly updated.</li><li>If I turned off my location in my smartphone, a pop up should ask him to enable it if he wants to be located.</li></ul></p> |
| **Result** | 60%  |
| **Comments** | <p>Locate yourself on the map first and whenever you explore the map it brings you back to your location.</p>  |

**Comment by thomasgauvin** [comment]
In this Acceptance Test, we needed to center the map to the current location of the user when the application starts. This is what was added. 
![CCG4](https://user-images.githubusercontent.com/35609369/77881569-467e5280-722d-11ea-8a24-187bb5b44a48.gif)

**Comment by mosaliza** [comment]
I use Android phone to test the app. This apk does not show the blue pin to locate me on the map. it centers on EV building. And it does not alert when the GPS is off.

**Comment by thomasgauvin** [comment]
When you install 

> I use Android phone to test the app. This apk does not show the blue pin to locate me on the map. it centers on EV building. And it does not alert when the GPS is off.

When you install the application, you must give permission to use your current location. This way, the application will center on your current location the next time you open the application. You can also click the current location button to center on your current location at any time.

**Comment by thomasgauvin** [comment]
The map will default to centering to the EV Builing if it does not have access to your current location

**Comment by mosaliza** [comment]
Passed.

**Comment by thomasgauvin** [comment]
Thank you!
