### ISSUE TITLE
CCG- #22 - As a user, I would like to be able to see the inner map of the building, so that I can clearly see what is on each of the floors of the building.

### ISSUE THREAD

**Issue by Hambrsoom** [Concordia-Campus-Guide/Concordia-Campus-Guide#190]
| **AT-4** | CCG- #22 - As a user, I would like to be able to see the inner map of the building, so that I can clearly see what is on each of the floors of the building. |
| --- | --- |
| **Acceptance Criteria** | <p>Given that I am using the map, <br>and that I click on an over layered building,<br>and that I choose to see the indoor map of the building from the info cards, <br>then, I should be able to:<br><ul><li>see an indoor map of the selected building</li><li>switch between floors inside the building</li></ul></p>|
| **Result** | 90% |
| **Comments** | <p> After you select the building, it should show the default floor selection (toppermost) floor</p> |

**Comment by thomasgauvin** [comment]
In this screen recording, we show that the current floor is selected on the floor picker when clicking on the building as per comments from our last meeting.

![CCG22](https://user-images.githubusercontent.com/35609369/77882534-264f9300-722f-11ea-97e5-09cc1b57e109.gif)

**Comment by mosaliza** [comment]
Accepted.
