### ISSUE TITLE
CCG- #38 - As a user, I would like to select an indoor location so that I can get indoor directions to or from this location.

### ISSUE THREAD

**Issue by Hambrsoom** [Concordia-Campus-Guide/Concordia-Campus-Guide#191]
| **AT-7** | CCG- #38 - As a user, I would like to select an indoor location so that I can get indoor directions to or from this location. |
| --- | --- |
| **Acceptance Criteria** | <p>Given that I am using the indoor map of a building, <br>then, I should be able to: <br> <ul> <li>~~select a room or a point on the map as a location~~</li> <li>select a departure location from a list when clicking on the *from* box </li><li>select a destination location by clicking on the *to* box.</li></ul></p>|
| **Result** |  |
| **Comments** |  |

**Comment by thomasgauvin** [comment]
![CCG38v2](https://user-images.githubusercontent.com/35609369/77880567-ec7c8d80-722a-11ea-8e0f-0d0116a1e9b0.gif)

**Comment by mosaliza** [comment]
Accepted.
