### ISSUE TITLE
CCG-9 - As a user, I would like to get directions from a source to a destination within the same building

### ISSUE THREAD

**Issue by Hambrsoom** [Concordia-Campus-Guide/Concordia-Campus-Guide#192]
| **AT- 8** | CCG- #9 - As a user, I would like to get directions from a source to a destination within the same building |
| --- | --- |
| **Acceptance Criteria** | <p>Given that I am using the indoor map of a building,<br>and then I click on get indoor directions,<br>and then I choose my source point,<br>and then I choose my destination point,<br>and then I should be able to:<ul><li>see the directions for the shortest path from point X (source) to point Y (destination) on the same floor or different floor</li><li>see the shortest paths on the map.</li></ul></p>|
| **Result** |  |
| **Comments** |  |

**Comment by thomasgauvin** [comment]
![CCG9v2](https://user-images.githubusercontent.com/35609369/77882349-d1ac1800-722e-11ea-941a-0641d9156854.gif)

**Comment by mosaliza** [comment]
Passed.
