### ISSUE TITLE
CCG-40 - As a user, I want to get indoor directions between two points that are located in separate buildings so that I can navigate through the campus.

### ISSUE THREAD

**Issue by Hambrsoom** [Concordia-Campus-Guide/Concordia-Campus-Guide#194]
| **AT-9** | CCG- #40 - As a user, I want to get indoor directions between two points that are located in separate buildings so that I can navigate through the campus. |
| --- | --- |
| **Acceptance Criteria** | <p>Given that I am using the indoor map of a building,<br>and then I choose my source point from one building,<br>and the I choose my destination point from another building,<br>then I should be able to:<br><ul><li>get the routes from one building to another using the tunnels</li><li>see the directions for the shortest path from point X (source) to point Y (destination) between 2 buildings.</li></ul></p>|
| **Result** |  |
| **Comments** |  |

**Comment by thomasgauvin** [comment]
![CCG40v2](https://user-images.githubusercontent.com/35609369/77881302-b0e2c300-722c-11ea-81b0-1f821f775a0e.gif)

**Comment by mosaliza** [comment]
Passed.
