### ISSUE TITLE
CCG-6 - As a user, I would like to select a desired location, so that I can get directions to or from this selected location

### ISSUE THREAD

**Issue by Hambrsoom** [Concordia-Campus-Guide/Concordia-Campus-Guide#195]
| **AT-10** | CCG- #6 - As a user, I would like to select a desired location, so that I can get directions to or from this selected location |
| --- | --- |
| **Acceptance Criteria** | <p> Given that I am using the map,<br>and then I click on the search button,<br>then I should be able to:<br><ul><li>choose the starting point by using my location on the map, entering the building’s address.</li><li>choose the destination point by entering the building’s address. </li><li>do this on both the Loyola and the SGW buildings</li></ul></p>|
| **Result** |  |
| **Comments** |  |

**Comment by thomasgauvin** [comment]
![CCG6](https://user-images.githubusercontent.com/35609369/77881017-f6eb5700-722b-11ea-8e37-3cb6a716c548.gif)

**Comment by mosaliza** [comment]
![Screenshot_20200405-181853_Concordia-Campus-Guide](https://user-images.githubusercontent.com/35632341/78511369-1de4e400-776a-11ea-8e83-6f4e4a18c4e7.jpg)
Please check the reason why the output includes tags in the list of steps!

**Comment by thomasgauvin** [comment]
![ccg-6](https://user-images.githubusercontent.com/35609369/79183657-0c41b300-7de0-11ea-83fb-ddf56b6c0ab6.gif)

**Comment by mosaliza** [comment]
Passed.
