### ISSUE TITLE
CCG-51 - As a user, I would like to be able to see the different routes across indoors and outdoors that can be taken, so that I can choose my preferred route.

### ISSUE THREAD

**Issue by Hambrsoom** [Concordia-Campus-Guide/Concordia-Campus-Guide#196]
| **AT- 11** | CCG- #51 - As a user, I would like to be able to see the different routes across indoors and outdoors that can be taken, so that I can choose my preferred route. |
| --- | --- |
| **Acceptance Criteria** | <p>Given that I chose my starting and ending points,<br>then I should be able to:<br><li>see each possible route according to the Google Routes, indoor paths, and Shuttle Routes</li><li>see the time and transit type.</li></p>|
| **Result** |  |
| **Comments** |  |

**Comment by thomasgauvin** [comment]
As can be seen in this recording, all trips work across google maps directions (in this case public transit) and indoor directions to the desired classroom (in this case H-819)

![ccg51](https://user-images.githubusercontent.com/35609369/79183787-74909480-7de0-11ea-9ff9-006ec91454e5.gif)

**Comment by mosaliza** [comment]
Passed.
