### ISSUE TITLE
CCG-7 - As a user, I would like to see the steps and directions of my selected route on the map, step by step.

### ISSUE THREAD

**Issue by Hambrsoom** [Concordia-Campus-Guide/Concordia-Campus-Guide#197]
| **AT-12** | CCG- #7 - As a user, I would like to see the steps and directions of my selected route on the map, step by step. |
| --- | --- |
| **Acceptance Criteria** | <p>Given that I chose the route to go somewhere,<br>then I should be able to:<br><li>see the directions on the map.</li><li>see the directions step by step.</li>|
| **Result** |  |
| **Comments** |  |

**Comment by thomasgauvin** [comment]
![CCG7v2](https://user-images.githubusercontent.com/35609369/77880365-80018e80-722a-11ea-8da2-749e73a8511a.gif)

**Comment by mosaliza** [comment]
Same issue as CCG6.

**Comment by thomasgauvin** [comment]
![ccg-7](https://user-images.githubusercontent.com/35609369/79183686-267b9100-7de0-11ea-98d1-882532d19ba3.gif)

**Comment by mosaliza** [comment]
Passed.
