### ISSUE TITLE
CCG-10 - As a student, I would like to be able to link my google calendars to the app so that I can get directions for my upcoming classes.

### ISSUE THREAD

**Issue by Hambrsoom** [Concordia-Campus-Guide/Concordia-Campus-Guide#198]
| **AT-13** | CCG-10 - As a student, I would like to be able to link my google calendars to the app so that I can get directions for my upcoming classes. |
| --- | --- |
| **Acceptance Criteria** |<p>Given that I am a student,<br>then I should be able to:<ul><li>Choose to give access or not to my Google Calendar.</li></ul></p>|
| **Result** |  |
| **Comments** |  |

**Comment by thomasgauvin** [comment]
![CCG10](https://user-images.githubusercontent.com/35609369/77879532-a3c3d500-7228-11ea-854b-53c716f5418f.gif)

**Comment by mosaliza** [comment]
Passed.
