### ISSUE TITLE
CCG-17 - As a student, I would like to easily get directions to my next class as indicated in my Google Calendar, so that I can easily get to my next class.

### ISSUE THREAD

**Issue by Hambrsoom** [Concordia-Campus-Guide/Concordia-Campus-Guide#199]
| **AT-14** | CCG- #17 - As a student, I would like to easily get directions to my next class as indicated in my Google Calendar, so that I can easily get to my next class. |
| --- | --- |
| **Acceptance Criteria** | <p>Given that I gave access to my Google Calendar,<br>then, I should be able to:<br><ul><li>select the directions to my next class.</li><li>get the locations and direction to my upcoming classes based on the next calendar event.</li>|
| **Result** |  |
| **Comments** |  |

**Comment by thomasgauvin** [comment]
![CCG17](https://user-images.githubusercontent.com/35609369/77879427-6a8b6500-7228-11ea-85c7-59305875ee92.gif)

**Comment by thomasgauvin** [comment]
In order to properly do so, please have an event in your calendar within 1 hour with the format specified in the wiki: https://github.com/Concordia-Campus-Guide/Concordia-Campus-Guide/wiki/Calendar-Integration

**Comment by mosaliza** [comment]
![Screenshot_20200405-185811_Chrome](https://user-images.githubusercontent.com/35632341/78512057-78347380-776f-11ea-861e-66e14067c5f2.jpg)
Let me know after I edit the location name how I can look for my next class. I set a class on my calendar as shown in the above pic with the location on hall building with8n one our but I can not see alerts for my next class.

**Comment by thomasgauvin** [comment]
Hi Sadegh,

The reason that it is not working is that you must add the event to your default android Calendar, which is the Google Calendar application.

**Comment by mosaliza** [comment]
Passed.

**Comment by thomasgauvin** [comment]
Thank you!
