### ISSUE TITLE
CCG-49 - As a student, I would like to be notified of my upcoming class an hour in advance, so that I can get to class on time.

### ISSUE THREAD

**Issue by Hambrsoom** [Concordia-Campus-Guide/Concordia-Campus-Guide#200]
| **AT-15** | CCG- #49 - As a student, I would like to be notified of my upcoming class an hour in advance, so that I can get to class on time|
| --- | --- |
| **Acceptance Criteria** | <p>Given that I am a student,<br>then, i open the application and I have a class in an hour or less,<br>then, I should be able to:<br><ul><li>see a pop-up shows up in the application 1h before class.</li><li>see that the pop-up includes information about the class.</li><li>cancel or get direction to the class.</li></p>|
| **Result** |  |
| **Comments** |  |

**Comment by thomasgauvin** [comment]
![CCG49](https://user-images.githubusercontent.com/35609369/77879158-c3a6c900-7227-11ea-98dc-fa218f7d35ca.gif)

**Comment by viveanban** [comment]
Gif explanation: The user opens the application and is prompted to get the directed to their next class. If they choose so, they will be directed to the list of routes to that class.

**Comment by thomasgauvin** [comment]
In order to properly do so, please have an event in your calendar within 1 hour with the format specified in the wiki: https://github.com/Concordia-Campus-Guide/Concordia-Campus-Guide/wiki/Calendar-Integration

**Comment by mosaliza** [comment]
Check CCG-17.

**Comment by thomasgauvin** [comment]
Since we passed the other issue CCG-17 related to the calendar, we will wait to get the approval from the PO to close this acceptance test.

**Comment by mosaliza** [comment]
Passed.
