### ISSUE TITLE
CCG-95 - As a user, I would like to be able to get the different routes taking the shuttle, so that I can easily know how to get to the other Concordia campus.

### ISSUE THREAD

**Issue by Hambrsoom** [Concordia-Campus-Guide/Concordia-Campus-Guide#202]
| **AT-** | CCG-#95 - As a user, I would like to be able to get the different routes taking the shuttle, so that I can easily know how to get to the other Concordia campus. |
| --- | --- |
| **Acceptance Criteria** |<p> Given that I am a student,<br>when, I open the application,<br>and I am looking to go from one campus to the other using the shuttle,<br>then, I should be able to:<br><ul><li>select shuttle as a transit option</li><li>see approximate time it takes for the shuttle</li><li>see a list of route options using the shuttle (say next 2 shuttles)</li></p>|
| **Result** |  |
| **Comments** |  |

**Comment by thomasgauvin** [comment]
![CCG95](https://user-images.githubusercontent.com/35609369/77878952-7fb3c400-7227-11ea-9819-11f598a32185.gif)

**Comment by viveanban** [comment]
Gif explanation: The user chooses to get the directions between buildings from the Loyala campus and SGW campus. They choose the shuttle option and see the routes generated by that transit type.

**Comment by mosaliza** [comment]
Passed.
