### ISSUE TITLE
CCG - 11 - Give that I am a user, then, I open the application, then, I should be able to:  choose a type of points of interest from a list of options (elevator, washrooms, etc.) see a list of points according to his chosen type on the map select a point and obtain directions see an indoor.

### ISSUE THREAD

**Issue by Hambrsoom** [Concordia-Campus-Guide/Concordia-Campus-Guide#205]
| **AT-17** | CCG - #11 - Give that I am a user, then, I open the application, then, I should be able to:  choose a type of points of interest from a list of options (elevator, washrooms, etc.) see a list of points according to his chosen type on the map select a point and obtain directions see an indoor. |
| --- | --- |
| **Acceptance Criteria** |<p>Given that I am a user,<br>then, I open the application,<br>then, I should be able to:<br> <ul><li>choose a type of points of interest from a list of options (elevator, washrooms, etc.)</li><li> see a list of points according to his chosen type on the map</li><li>select a point and obtain directions</li></ul></p> |
| **Result** |  |
| **Comments** |  |

**Comment by thomasgauvin** [comment]
![CCG11](https://user-images.githubusercontent.com/35609369/77878625-ba692c80-7226-11ea-9a41-7a249e953598.gif)

**Comment by viveanban** [comment]
Gif explanation:  The user opens the application, slides up the explore card and selects a point of interest category that they would like to see. The 10 closest point of interests are displayed on the map and the map zooms and centers on the closest cluster. When the user clicks on a point of interest, the routes to that point are populated.

**Comment by mosaliza** [comment]
Passed.
