### ISSUE TITLE
CCG - 94 - As a user, I would like to see my different route options for outdoor directions according to my transit preferences so that I can easily navigate from one building to another.

### ISSUE THREAD

**Issue by Hambrsoom** [Concordia-Campus-Guide/Concordia-Campus-Guide#206]
| **AT-18** | CCG - #94 - As a user, I would like to see my different route options for outdoor directions according to my transit preferences so that I can easily navigate from one building to another.|
| --- | --- |
| **Acceptance Criteria** |<p>Given that I am a user,<br>then, i open the application,<br>then, i search for the direction between two places,<br>then i should be able to:<br><ul><li>select my transit preferences</li><li>get a list of possible routes</li><li>see the time that each route takes</li></ul></p>|
| **Result** |  |
| **Comments** |  |

**Comment by thomasgauvin** [comment]
![CCG94](https://user-images.githubusercontent.com/35609369/77878362-20a17f80-7226-11ea-88d7-183b2e039263.gif)

**Comment by viveanban** [comment]
Gif explanation: Once the application is opened, the user searches for the description between 2 buildings (Hall and Vanier Library). They then choose different transit types and see their proposed routes change according to the transit type.

**Comment by mosaliza** [comment]
Passed.
