### ISSUE TITLE
CCG-156 - As a user, I would like to be able to toggle my preferences from a side menu, so that I can customize the behavior of the application.

### ISSUE THREAD

**Issue by Hambrsoom** [Concordia-Campus-Guide/Concordia-Campus-Guide#277]
| **AT-19** | CCG-156 - As a user, I would like to be able to toggle my preferences from a side menu, so that I can customize the behavior of the application. |
| --- | --- |
| **Acceptance Criteria** | <p>Given that I am on the main page,<br>and that I clicked on the hamburger icon<br>then I should see,<br><li>A side menu popping up on the left side of the application as an overlay on top of the main page as designed in our Figma mockups</li></p>
| **Result** |  |
| **Comments** |  |

**Comment by thomasgauvin** [comment]
![ccg156](https://user-images.githubusercontent.com/35609369/79183508-aa814900-7ddf-11ea-9b01-b68ea87d454c.gif)

**Comment by mosaliza** [comment]
Passed.
