### ISSUE TITLE
CCG-160 - As a user, I would like to be able to get routes according to my accessibility preferences, so that I can navigate according to my accessibility/handicap/staff.

### ISSUE THREAD

**Issue by Hambrsoom** [Concordia-Campus-Guide/Concordia-Campus-Guide#278]
| **AT-20** | CCG- #160 - As a user, I would like to be able to get routes according to my accessibility preferences, so that I can navigate according to my accessibility/handicap/staff. |
| --- | --- |
| **Acceptance Criteria** | <p>Given that I am on the hamburger menu,<br>and that I toggled either Accessibility or Staff <br>OR<br>Given that I am on the Routes Activity page,<br>and that I pressed the Disability button,<br>then I should see,<br><li>The suggested routes change according to my preferences set (handicap, staff). Ex: for handicaps, suggested routes do not include stairs or escalators but rather elevators.</li>|
| **Result** |  |
| **Comments** |  |

**Comment by thomasgauvin** [comment]
Recommended trip:

Enter location and destination as H-9 983 and H-8 855. You will notice that when accessibility is turned off, the trip will go through the stairs, whereas when the accessibility is turned on, the trip will take the elevators

**Comment by mosaliza** [comment]
Passed.
