### ISSUE TITLE
CCG-158 - As a user, I would like to be able to browse the application in french, so that I can understand how to use the application as a french-speaker.

### ISSUE THREAD

**Issue by Hambrsoom** [Concordia-Campus-Guide/Concordia-Campus-Guide#279]
| **AT-21** | CCG- #158 - As a user, I would like to be able to browse the application in french, so that I can understand how to use the application as a french-speaker. |
| --- | --- |
| **Acceptance Criteria** |<p>Given that I am on the hamburger menu,<br>and that I toggled the French button<br>then I should see,<br><li>The menu, step-by-step directions, buttons, and application text written in French</li><li>Data from services and departments, as they are static names from the University, written in English (not translated)</li></p>|
| **Result** |  |
| **Comments** |  |

**Comment by thomasgauvin** [comment]
![ccg158](https://user-images.githubusercontent.com/35609369/79183058-6772a600-7dde-11ea-9a12-b10e55df77de.gif)

**Comment by mosaliza** [comment]
Passed.
