### ISSUE TITLE
CCG-157 - As a user, I would like to be able to select a classroom from the map, so that I can select my destination by selecting it directly from the map

### ISSUE THREAD

**Issue by Hambrsoom** [Concordia-Campus-Guide/Concordia-Campus-Guide#280]
| **AT-22** | CCG- #157 - As a user, I would like to be able to select a classroom from the map, so that I can select my destination by selecting it directly from the map |
| --- | --- |
| **Acceptance Criteria** |<p> Given that I am on the indoor map,<br>and that I clicked on a classroom,<br>then I should see,<li>An info card pop up at the bottom of the application giving me the option to get directions to that classroom from my current location.</li></p>|
| **Result** |  |
| **Comments** |  |

**Comment by thomasgauvin** [comment]
![ccg157](https://user-images.githubusercontent.com/35609369/79182349-96881800-7ddc-11ea-8fcd-509d2bd9f9bd.gif)

**Comment by mosaliza** [comment]
Passed.
