### ISSUE TITLE
CCG-176 - As a user, I would like to be able to see the different points of interests such as water fountains, lounges, so that I can find the points of interest on campus.

### ISSUE THREAD

**Issue by Hambrsoom** [Concordia-Campus-Guide/Concordia-Campus-Guide#281]
| **AT-23** | CCG- #176 - As a user, I would like to be able to see the different points of interests such as water fountains, lounges, so that I can find the points of interest on campus. |
| --- | --- |
| **Acceptance Criteria** | <p>Given that I am on the indoor map, <br>and that I drag the Explore card up,<br>and that I click on Water Fountains or Lounges,<br>then I should see,<br><li>The different markers for the POI selected, on the map</li><li>The closest POI marker to be centered on the map.</li></p> |
| **Result** |  |
| **Comments** |  |

**Comment by thomasgauvin** [comment]
![ccg176](https://user-images.githubusercontent.com/35609369/79181743-1ca35f00-7ddb-11ea-9f48-7f1a37c5cd36.gif)

**Comment by mosaliza** [comment]
Passed.
