### ISSUE TITLE
Search Activity Page does not match figma

### ISSUE THREAD

**Issue by narrapangan** [Concordia-Campus-Guide/Concordia-Campus-Guide#285]
**Description**
As indicated in title, search activity page does not match figma. 

**Goals**
Search Bar is rectangular

**Reference to User stories**

**Difficulty (Scale 1-10)**
1

**Additional documentation (Optional)**
https://www.figma.com/file/SVRvWbm54wygEM3RnRje1r/Octocats-Minicap?node-id=424%3A1586

**Comment by viveanban** [comment]
[Prototype has been changed to have a rounded search bar. ](https://www.figma.com/file/SVRvWbm54wygEM3RnRje1r/Octocats-Minicap?node-id=424%3A1586)
This fix is no longer needed.
