### ISSUE TITLE
The link in the google calendar event is not clickable

### ISSUE THREAD

**Issue by Hambrsoom** [Concordia-Campus-Guide/Concordia-Campus-Guide#298]
**Describe the bug**
When you open an event on your google calendar that it is about a class, we should have a clickable link in the notes. Once the user click on it, the application should open.

**User Story Reference (Optional)**
#50 

**To Reproduce**
1) Create an event on google calendar at the next hour with the right structure. 
2) Open our app. 
3) You should receive a notification.
4) Ignore the notification and close the app.
5) Open the event on the google calendar.

**Expected behavior**
In the notes, we should have a clickable link to our app. However, we have only the sentence saying Go To ConuMaps.

**Screenshots**
![image](https://user-images.githubusercontent.com/32947679/79047158-fca94b00-7be2-11ea-9d25-f5c67e8aebdd.png)

**Comment by thomasgauvin** [comment]
Cannot reproduce

**Comment by thomasgauvin** [comment]
You can see the screen recording here that every works as intended: https://octocatsminicap.slack.com/files/USER7JY4X/F011YMX76E5/untitled.webm

**Comment by thomasgauvin** [comment]
Won't do since this is caused by a lack of support from certain third-party calendar applications
