### ISSUE TITLE
Show indoor directions from point X to Y between buildings

### ISSUE THREAD

**Issue by thomasgauvin** [Concordia-Campus-Guide/Concordia-Campus-Guide#40]
As a user, I want to get indoor directions between two points that are located in separate buildings so that I can navigate through the campus.

Acceptance Criteria:
Given that I am using the indoor map of a building,
and then I choose my source point from one building,
and the I choose my destination point from another building,
and then I should be able to:
- get the routes from one building to another using the tunnels or other indoor passage.
- see the directions for the shortest path from point X (source) to point Y (destination) between 2 buildings.
-see the alternative paths and shortest paths are shown on the map.-
-save my preference of accessibility (wheelchair accessibility, no stairs, etc…).-
-see the pin of my current location and target destination across floors.-

**Comment by viveanban** [comment]
Internal timeline: 6-13 March
