### ISSUE TITLE
Unexpected buttons appearing when clicking on a building

### ISSUE THREAD

**Issue by tarekait1996** [Concordia-Campus-Guide/Concordia-Campus-Guide#66]
**Describe the bug**
Two buttons show up on the screen when clicking on a building overlay. These redirect us to google map and should not be visible normally

**User Story Reference (Optional)**
#21 

**To Reproduce**
- Open the application
- Click on H building overlay
- on the bottom, you will see two small icons appearing

**Expected behavior**
The two buttons should not appear

**Screenshots**
![Screenshot_1582909177.png](https://images.zenhubusercontent.com/5e17476e0eda874c7740ff14/ecf470ac-fcf0-4d49-8113-7161d06e3077)

**Comment by Hambrsoom** [comment]
Bug has been fixed :)
