### ISSUE TITLE
Show steps and directions on map for selected route

### ISSUE THREAD

**Issue by tarekait1996** [Concordia-Campus-Guide/Concordia-Campus-Guide#7]
As a user, I would like to see the steps and directions of my selected route on the map, with step-by-step directions.

Acceptance Criteria:
Given that I chose the route to go somewhere,
then I should be able to:
- see the directions on the map.
- see the directions step by step.
- see my location getting tracked as I move throughout the steps.

![image](https://user-images.githubusercontent.com/35609369/75819393-98d06e80-5d68-11ea-9844-f6eac8d8a5bd.png)

Story tasks:
1. Show directions on the maps
2. Show the steps
3. Test

**Comment by thomasgauvin** [comment]
![image](https://user-images.githubusercontent.com/35609369/75819367-8d7d4300-5d68-11ea-983a-be8bf75b2d2c.png)
