### ISSUE TITLE
 Show directions from point X to Y within a building

### ISSUE THREAD

**Issue by tarekait1996** [Concordia-Campus-Guide/Concordia-Campus-Guide#9]
As a user, I would like to get directions from a source to a destination  within the same building

Acceptance Criteria:
Given that I am using the indoor map of a building,
and then I click on get indoor directions,
and then I choose my source point,
and then I choose my destination point,
and then I should be able to:
- see the directions for the shortest path from point X (source) to point Y (destination) on the same floor or different floor
- see alternative paths and shortest paths on the map.
- automatically use my preference of accessibility (wheelchair accessibility, no stairs, etc...)
- see the pin of my current location and target destination across floors.

**Comment by viveanban** [comment]
Internal timeline: 6-13 March
