### ISSUE TITLE
Display Routes of Google Maps + UI

### ISSUE THREAD

**Issue by thomasgauvin** [Concordia-Campus-Guide/Concordia-Campus-Guide#94]
As a user, I would like to see my different route options for outdoor directions according to my transit preferences so that I can easily navigate from one building to another.

More details: This step includes calling the GMap API and getting the different routes available. This story also includes displaying the list of the different routes, with a time that it takes to complete the route.

See pic below:
![image.png](https://images.zenhubusercontent.com/5e17455ee6c0ec60e23dc1a0/a45d4913-51cd-4b80-b5b9-92976f3d62b2)

Acceptance criteria:
Given that I am a user, 
then, i open the application,
then, i search for the direction between two places,
then i should be able to:
- select his transit preferences
- get a list of possible routes
- see the time that each route takes

Steps:
1- Research GMap API
2- Implement transit buttons
3- Get routes from GMap
4- Display routes on Routes page
5- Testing

**Comment by imabhijit** [comment]
Hi, it's not working for me when I try to select the location, I have PMed you the error code please take a look at it. 
Steps to reproduce:
1) I clicked on the search button
2) Select Hall F. Building from the dropdown
Then it crashes

**Comment by imabhijit** [comment]
I also can't see the UI for selecting different transit types, is that expected behaviour?

**Comment by imabhijit** [comment]
I also cannot see any routes yet, but I am guessing that it is currently the expected behavior?
